name: afm_env
channels:
  - defaults
  - afm
  - rmg
  - KEHANG
  - rdkit
dependencies:
  - rmg::cantera
  - dde
  - jupyter
  - rmg::lpsolve55
  - matplotlib
  - mpmath
  - nose
  - numpy
  - pandas
  - rmg::pydas >=1.0.1
  - rmg::quantities
  - rdkit::rdkit
  - afm::rmg==2.4.1.1
  - afm::rmgdatabase
  - scikit-learn
  - scipy
  - tqdm
  - xlwt
