name: afm_env
channels:
  - defaults
  - rmg
  - KEHANG
dependencies:
  - numpy
  - rmg::quantities
  - scipy
  - rmg::rdkit
  - rmg::lpsolve55
  - rmg::pydas >=1.0.1
  - matplotlib
  - rmg::cantera
  - xlwt
  - nose
  - pandas
  - KEHANG::rmg
  - KEHANG::rmgdatabase